### ISSUE TITLE
Move this getter to parent class to reduce duplicated code in extended classes

### ISSUE THREAD

**Issue by Japoivvb** [JuditoCHAN/M07_UF1_POO_Bank#1]
https://github.com/JuditoCHAN/M07_UF1_POO_Bank/blob/5600e94c89512a98b9b231768e26e33bf2885af1/src/ComBank/Transactions/WithdrawTransaction.php#L60

**Comment by JuditoCHAN** [comment]
Cambio realizado. 
![image](https://github.com/user-attachments/assets/75f5333d-c16b-4a41-8a2b-7b1feca6f8fa)
